---
 - name: Ping playbook
   hosts: ovh
   vars_files:
     - host_vars/main.yml
   tasks:
     - name: Ping
       ansible.builtin.ping: 
     - name: Print Hello World
       ansible.builtin.debug:
         msg: "Hello World!"
